Add support for nodes and edges in geographical space
thomasp85/ggraph pull request #357
Opened 2024-01-19 19:30 UTC by loreabad6

See #275 for details. Main issues for now are:

1. the implementation of GeomEdgeSf in geom_edge_sf.R
2. facetting for certain cases
3. handling `sfnetworks` and `sf` in the NAMESPACE

2024-01-22 21:47 UTC, thomasp85 requested changes
This is really good. I have made a bunch of suggestions but most are cosmetic

2024-01-22 21:47 UTC, thomasp85 commented on R/tbl_graph.R
> +  }
Is this classing being used anywhere?

2024-01-22 21:47 UTC, thomasp85 commented on R/tbl_graph.R
> +  else as_tbl_graph(graph)
```suggestion
  if (inherits(graph, "sfnetwork")) {
    graph
  } else {
    as_tbl_graph(graph)
  }
```

2024-01-22 21:47 UTC, thomasp85 commented on R/layout_sf.R
> +  }
```suggestion
  check_installed("sf")
```

2024-01-22 21:47 UTC, thomasp85 commented on R/layout_sf.R
> +    stop("Layout 'sf' needs an 'sfnetwork' graph.", call. = FALSE)
```suggestion
    cli::cli_abort("The 'sf' layout needs an {.cls sfnetwork} graph.")
```

2024-01-22 21:47 UTC, thomasp85 commented on R/layout_sf.R
> +  nodes$circular <- FALSE
```suggestion
  nodes <- data_frame0(x = x, y = y, circular = FALSE)
```

2024-01-22 21:47 UTC, thomasp85 commented on R/layout_sf.R
> +  nodes <- cbind(nodes, extra_data[, !names(extra_data) %in% names(nodes), drop = FALSE])
```suggestion
  nodes <- combine_layout_nodes(nodes, extra_data)
```

2024-01-22 21:47 UTC, thomasp85 commented on R/geom_edge_sf.R
> +)
```suggestion
GeomEdgeSf = ggproto("GeomEdgeSf", GeomSf,
  draw_panel = function(data, panel_params, coords) {
    names(data) <- sub('edge_', '', names(data))
    names(data)[names(data) == 'width'] <- 'size'
    GeomSf$draw_panel(data, panel_params, coords)
  },
  draw_key = GeomEdgePath$draw_key,
  default_aes = aes(
    edge_colour = 'black', edge_width = 0.5, edge_linetype = 1,
    edge_alpha = NA
  ),
  rename_size = FALSE
)

```

2024-01-22 21:47 UTC, thomasp85 commented on R/aaa.R
> +        stop('filter must be logical')
```suggestion
        cli::cli_abort('{.field filter} must be logical')
```

2024-01-22 22:15 UTC, thomasp85 commented
As for your list of things, I've addressed 1) in my suggestions, 2) is unknown to me - do you have some examples of failures and I'll be happy to look into them, and 3) is also handled in the suggestions I think.

2024-01-23 13:56 UTC, loreabad6 commented on R/tbl_graph.R
> +  }
No, I'll remove it

2024-01-23 14:36 UTC, loreabad6 commented
Thank you for the suggestions, I have incorporated them. 

Following up on the list:

1. GeomEdgeSf now recognizes aesthetics but does not recognize parameters outside `aes()` unless `edge_*` is added.
```r
ggraph(net, 'sf') +
  geom_node_sf(aes(color = central)) +
  geom_edge_sf(color = 'grey')
#> Warning in layer_sf(geom = GeomEdgeSf, data = data, mapping = mapping, stat = StatFilterSf, :
#> Ignoring unknown parameters: `colour`
```

![](https://i.imgur.com/GqHjvdx.png)<!-- -->

``` r

### Need to write edge_* to get parameter
ggraph(net, 'sf') +
  geom_node_sf(aes(color = central)) +
  geom_edge_sf(edge_color = 'grey')
```

![](https://i.imgur.com/iYCwuCm.png)<!-- -->

2024-01-23 14:38 UTC, loreabad6 commented
And an example of a failed facetting case for point 2:

``` r
library(sfnetworks)
library(tidygraph)
library(ggraph)

net = roxel %>% 
  as_sfnetwork() %>% 
  mutate(centrality = centrality_betweenness()) %>% 
  mutate(central = ifelse(centrality > 1000, T, F)) %>% 
  activate('edges') %>% 
  mutate(azimuth = edge_azimuth(), length = edge_length())

ggraph(net, 'sf') +
  geom_node_sf(color = 'red', size = 0.05) +
  geom_edge_sf(aes(color = type)) +
  facet_graph(type ~ central) 
#> Warning: Unknown or uninitialised column: `.ggraph.index`.
#> Error in `x[i, , drop = drop]`:
#> ! Can't subset rows with `i`.
#> ✖ Logical subscript `i` must be size 1 or 701, not 0.
#> Backtrace:
#>      ▆
#>   1. ├─base::tryCatch(...)
#>   2. │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>   3. │   ├─base (local) tryCatchOne(...)
#>   4. │   │ └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>   5. │   └─base (local) tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
#>   6. │     └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>   7. │       └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>   8. ├─base::withCallingHandlers(...)
#>   9. ├─base::saveRDS(...)
#>  10. ├─base::do.call(...)
#>  11. ├─base (local) `<fn>`(...)
#>  12. ├─global `<fn>`(input = base::quote("cheap-stoat_reprex.R"))
#>  13. │ └─rmarkdown::render(input, quiet = TRUE, envir = globalenv(), encoding = "UTF-8")
#>  14. │   └─knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
#>  15. │     └─knitr:::process_file(text, output)
#>  16. │       ├─knitr:::handle_error(...)
#>  17. │       │ └─base::withCallingHandlers(...)
#>  18. │       ├─base::withCallingHandlers(...)
#>  19. │       ├─knitr:::process_group(group)
#>  20. │       └─knitr:::process_group.block(group)
#>  21. │         └─knitr:::call_block(x)
#>  22. │           └─knitr:::block_exec(params)
#>  23. │             └─knitr:::eng_r(options)
#>  24. │               ├─knitr:::in_input_dir(...)
#>  25. │               │ └─knitr:::in_dir(input_dir(), expr)
#>  26. │               └─knitr (local) evaluate(...)
#>  27. │                 └─evaluate::evaluate(...)
#>  28. │                   └─evaluate:::evaluate_call(...)
#>  29. │                     ├─evaluate (local) handle(...)
#>  30. │                     │ └─base::try(f, silent = TRUE)
#>  31. │                     │   └─base::tryCatch(...)
#>  32. │                     │     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  33. │                     │       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  34. │                     │         └─base (local) doTryCatch(return(expr), name, parentenv, handler)
#>  35. │                     ├─base::withCallingHandlers(...)
#>  36. │                     ├─base::withVisible(value_fun(ev$value, ev$visible))
#>  37. │                     └─knitr (local) value_fun(ev$value, ev$visible)
#>  38. │                       └─knitr (local) fun(x, options = options)
#>  39. │                         ├─base::withVisible(knit_print(x, ...))
#>  40. │                         ├─knitr::knit_print(x, ...)
#>  41. │                         └─knitr:::knit_print.default(x, ...)
#>  42. │                           └─evaluate (local) normal_print(x)
#>  43. │                             ├─base::print(x)
#>  44. │                             └─ggplot2:::print.ggplot(x)
#>  45. │                               ├─ggplot2::ggplot_build(x)
#>  46. │                               ├─ggraph:::ggplot_build.ggraph(x)
#>  47. │                               ├─base::NextMethod() at ggraph/R/ggraph.R:149:3
#>  48. │                               └─ggplot2:::ggplot_build.ggplot(x)
#>  49. │                                 └─layout$setup(data, plot$data, plot$plot_env)
#>  50. │                                   └─ggplot2 (local) setup(..., self = self)
#>  51. │                                     └─base::lapply(...)
#>  52. │                                       └─ggplot2 (local) FUN(X[[i]], ...)
#>  53. │                                         └─ggraph (local) map_data(...)
#>  54. │                                           └─base::lapply(...) at ggraph/R/facet_graph.R:157:9
#>  55. │                                             └─ggraph (local) FUN(X[[i]], ...)
#>  56. │                                               ├─data[data$.ggraph.index %in% nodes, , drop = FALSE] at ggraph/R/facet_graph.R:158:11
#>  57. │                                               └─sf:::`[.sf`(data, data$.ggraph.index %in% nodes, , drop = FALSE) at ggraph/R/facet_graph.R:158:11
#>  58. │                                                 ├─x[i, , drop = drop]
#>  59. │                                                 └─tibble:::`[.tbl_df`(x, i, , drop = drop)
#>  60. │                                                   └─tibble:::vectbl_as_row_index(i, x, i_arg)
#>  61. │                                                     └─tibble:::vectbl_as_row_location(i, nr, i_arg, assign, call)
#>  62. │                                                       ├─tibble:::subclass_row_index_errors(...)
#>  63. │                                                       │ └─base::withCallingHandlers(...)
#>  64. │                                                       └─vctrs::vec_as_location(...)
#>  65. └─vctrs (local) `<fn>`()
#>  66.   └─vctrs:::stop_indicator_size(...)
#>  67.     └─rlang::cnd_signal(...)
```

2024-01-25 07:15 UTC, thomasp85 commented on R/geom_edge_sf.R
> +      params = list2(na.rm = FALSE, ...)
```suggestion
      params = expand_edge_aes(list2(na.rm = FALSE, ...))
```

2024-01-25 07:16 UTC, thomasp85 commented
The edge param thing was an oversight when I made the last batch of suggestions.

Let me have a look at the facet thing

2024-01-25 07:42 UTC, thomasp85 commented
So, it seems everything works if `geom_node_sf()` follows the behaviour of the other node geoms and set `data = NULL` rather than `data = get_sf_nodes()`. Would there be any concern with this? It seems all the relevant CRS information is captured in the `geometry` column in the layout so `get_sf_nodes()` is not needed

2024-01-25 07:43 UTC, thomasp85 commented on R/geom_node_sf.R
> +geom_node_sf <- function(mapping = NULL, data = get_sf_nodes(),
```suggestion
geom_node_sf <- function(mapping = NULL, data = NULL,
```

2024-01-25 07:43 UTC, thomasp85 commented on R/geom_node_sf.R
> +}
```suggestion

```

2024-01-29 08:30 UTC, thomasp85 commented
Yeah, I can see the CRS are not picked up with the basic layout as nodes

2024-01-29 08:31 UTC, thomasp85 commented on R/geom_node_sf.R
> +    nodes <- sf::st_as_sf(attr(layout, "graph"), "nodes")
```suggestion
    nodes <- sf::st_as_sf(layout)
```

2024-01-29 08:32 UTC, thomasp85 commented on R/geom_node_sf.R
> +    nodes <- sf::st_as_sf(attr(layout, "graph"), "nodes")
I believe this should be enough to solve the remaining issues

2024-01-29 13:20 UTC, loreabad6 commented
Thank you very much for reviewing this @thomasp85, I tested again and seems like all the issues I raised work now.

2024-01-29 14:00 UTC, thomasp85 commented
Great - can I get you to add a NEWS bullet as well

2024-01-29 14:12 UTC, loreabad6 commented
> Great - can I get you to add a NEWS bullet as well

Done!

2024-01-29 14:22 UTC, merged

2024-01-29 14:22 UTC, thomasp85 commented
Thank you!!!